Apps/urls.py
from django.urls import include, path
from django.contrib import admin

from theme import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('employee_cbv/', include('employee_cbv.urls', namespace='employee_cbv')),
    #path('employee_attendance/', include('employee_attendance', namespace='employee_attendance')),
    #path('auth_ua/', include('auth_ua', namespace='auth_ua')),
    #path('holidays/', include('holidays', namespace='holidays')),
    #path('books_fbv_user/', include('books_fbv_user.urls', namespace='books_fbv_user')),
    path('', views.home),
]

employee_cbv/urls.py
from django.urls import path

from . import views

app_name = 'employee_cbv'

urlpatterns = [
  path('', views.EmployeeList.as_view(), name='employee_list'),
  path('new', views.EmployeeCreate.as_view(), name='employee_new'),
  path('edit/<int:pk>', views.EmployeeUpdate.as_view(), name='employee_edit'),
  path('delete/<int:pk>', views.EmployeeDelete.as_view(), name='employee_delete'),
]

theme/urls.py
from django.conf.urls import url
from . import views

theme/models.py
from django.db import models

# Create your models here.

theme/views.py
from django.shortcuts import render

# Create your views here.
def home(request):
    return render(request, "home.html")

theme/templates/base.html
<html>
<head>
    <title></title>
    
    <style><!--
    body {
        font-family: Arial, Helvetica, sans-serif;
        width:800px;
        margin:auto;
    }
    a { 
        color:#0000EE;
        text-decoration:none;
    }
    a:hover {    
        text-decoration:underline;
    }
    --></style>
</head>
<body class="hold-transition skin-blue sidebar-mini">
<div class="wrapper">
    <header class="main-header">
    <!-- Logo -->
    <a href="index2.html" class="logo">
      <!-- mini logo for sidebar mini 50x50 pixels -->
      <span class="logo-mini"><b>A</b>LT</span>
      <!-- logo for regular state and mobile devices -->
      <span class="logo-lg"><b>Admin</b>LTE</span>
    </a>
    <!-- Header Navbar: style can be found in header.less -->
    <nav class="navbar navbar-static-top">
      <!-- Sidebar toggle button-->
      <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
        <span class="sr-only">Toggle navigation</span>
      </a>

    <div id="header">
        <h1><a href="/">Django CRUD Example</a></h1>
    </div><!-- header -->
    <div id="content">
        {% block content %}
        {% endblock %}
    </div><!-- content -->
</body>
</html>

theme/templates/home.html
{% extends "base.html" %}

{% block content %}

<a href="{% url 'employee_cbv:employee_list' %}">Employee List</a><br>
<a href="{% url 'auth_ua:auth_ua_list' %}">Login List</a><br>
<a href="{% url 'employee_attendance:employee_attendance_list' %}">Employee Attedace</a><br>
<a href="{% url 'holidays:holidays_list' %}">Holidays List</a><br>
{% comment %} <a href="{% url 'employee_fbv_user:employee_list' %}">Function Based Views with User Access</a><br>     {% endcomment %}

{% endblock %}