Apps/urls.py
from django.urls import include, path
from django.contrib import admin

from theme import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('employee_cbv/', include('employee_cbv.urls', namespace='employee_cbv')),
    #path('employee_attendance/', include('employee_attendance', namespace='employee_attendance')),
    #path('auth_ua/', include('auth_ua', namespace='auth_ua')),
    #path('holidays/', include('holidays', namespace='holidays')),
    #path('books_fbv_user/', include('books_fbv_user.urls', namespace='books_fbv_user')),
    path('', views.home),
]

employee_cbv/urls.py
from django.urls import path

from . import views

app_name = 'employee_cbv'

urlpatterns = [
  path('', views.EmployeeList.as_view(), name='employee_list'),
  path('new', views.EmployeeCreate.as_view(), name='employee_new'),
  path('edit/<int:pk>', views.EmployeeUpdate.as_view(), name='employee_edit'),
  path('delete/<int:pk>', views.EmployeeDelete.as_view(), name='employee_delete'),
]

holidays/models.py
from django.db import models
from django.urls import reverse

from django.shortcuts import render

# Import Datetime
from datetime import datetime

# Create your models here.

class Holidays(models.Model):
    # Tahun_Baru_Masehi = '01-01',
    # 02-05 = 'Tahun Baru Imlek'
    # 03-07 = 'Hari Raya Nyepi'
    # 04-03 = 'Isra Miraj'
    # 04-19 = 'Jumat Agung'
    # 05-01 = 'Hari Buruh'
    # 05-19 = 'Hari Raya Waisak'
    # 05-30 = 'Kenaikan Isa Almasih'
    # 06-01 = 'Hari Lahir Pancasila'
    # 06-05 = 'Idul Fitri'
    # 06-06 = 'Idul Fitri'
    # 08-11 = 'Idul Adha'
    # 08-17 = 'Hari Kemerdekaan'
    # 09-01 = 'Tahun Baru Hijriyah'
    # 11-09 = 'Maulid Nabi'
    # 12-25 = 'Hari Natal'

    National_Holiday_List = (
        ('01-01','Tahun Baru Masehi'),
        ('02-05','Tahun Baru Imlek'),
        ('03-07','Hari Raya Nyepi'),
        ('04-03','Isra Miraj'),
        ('04-19','Jumat Agung'),
        ('05-01','Hari Buruh'),
        ('05-19','Hari Raya Waisak'),
        ('05-30','Kenaikan Isa Almasih'),
        ('06-01','Hari Lahir Pancasila'),
        ('06-05','Idul Fitri'),
        ('06-06','Idul Fitri'),
        ('08-11','Idul Adha'),
        ('08-17','Hari Kemerdekaan'),
        ('09-01','Tahun Baru Hijriyah'),
        ('11-09','Maulid Nabi'),
        ('12-25','Hari Natal'),
    )

    Mass_Leave_List = (
        ('06-03','Cuti Bersama 1'),
        ('06-04','Cuti Bersama 1'),
        ('06-07','Cuti Bersama 2'),
        ('12-24','Cuti Bersama 3'),
    )

    year = models.DateField()
    date_f = models.DateField()
    national_holidays = models.CharField(max_length=30,choices=National_Holiday_List)
    cuti_bersama = models.CharField(max_length=30,choices=Mass_Leave_List)


    # def __str__(self):
    #     return self.date_f

    # def _str_(self):
	#     return "{}.{}".format(self.id,self.date_f)

    def get_absolute_url(self):
        return reverse('holidays:holidays_edit', kwargs={'pk': self.pk})

    #     NAMA_KETERANGAN = (
    #     ('Tahun Baru Masehi','Tahun Baru Masehi'),
    #     ('Tahun Baru Imlek','Tahun Baru Imlek'),
    #     ('Hari Raya Nyepi','Hari Raya Nyepi'),
    #     ('Isra Miraj','Isra Miraj'),
    #     ('Jumat Agung','Jumat Agung'),
    #     ('Hari Buruh','Hari Buruh'),
    #     ('Hari Raya Waisak','Hari Raya Waisak'),
    #     ('Kenaikan Isa Almasih','Kenaikan Isa Almasih'),
    #     ('Hari Lahir Pancasila','Hari Lahir Pancasila'),
    #     ('Cuti Bersama 1','Cuti Bersama'),
    #     ('Idul Fitri','Idul Fitri'),
    #     ('Cuti Bersama 2','Cuti Bersama'),
    #     ('Idul Adha','Idul Adha'),
    #     ('Hari Kemerdekaan','Hari Kemerdekaan'),
    #     ('Tahun Baru Hijriyah','Tahun Baru Hijriyah'),
    #     ('Maulid Nabi','Maulid Nabi'),
    #     ('Cuti Bersama 3','Cuti Bersama'),
    #     ('Hari Natal','Hari Natal'),
    # )

    # NH_CHOICES=(
    #     ('1 Januari','1 Januari'),       #Tahun Baru Masehi
    #     ('5 Februari','5 Februari'),     #Tahun Baru Imlek 
    #     ('7 Maret','7 Maret'),           #Hari Raya Nyepi
    #     ('3 April','3 April'),           #Isra Miraj
    #     ('19 April','19 April'),         #Jumat Agung
    #     ('1 Mei','1 Mei'),               #Hari Buruh
    #     ('19 Mei','19 Mei'),             #Hari Raya Waisak
    #     ('30 Mei','30 Mei'),             #Kenaikan Isa Almasih
    #     ('1 Juni','1 Juni'),             #Hari Lahir Pancasila
    #     ('5 Juni','5 Juni'),             #Idul Fitri
    #     ('6 Juni','6 Juni'),             #Idul Fitri
    #     ('11 Agustus','11 Agustus'),     #Idul Adha
    #     ('17 Agustus','17 Agustus'),     #Hari Kemerdekaan
    #     ('1 September','1 September'),   #Tahun Baru Hijriyah
    #     ('9 November','9 November'),     #Maulid Nabi
    #     ('25 Desember','25 Desember'),   #Hari Natal
        
    #     )
    # CB_CHOICES=(
    #     ('3 Juni','3 Juni'),             #Cuti Bersama 1
    #     ('4 Juni','4 Juni'),             #Cuti Bersama 1
    #     ('7 Juni','7 Juni'),             #Cuti Bersama 2
    #     ('24 Desember','24 Desember'),   #Cuti Bersama 3
    #     )

holidays/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render

# Import Datetime class
from datetime import datetime

from django.http import HttpResponse
from django.views.generic import TemplateView,ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from django.utils.timezone import datetime
from holidays.models import Holidays
# Create your views here.

class HolidayList(ListView):
    model = Holidays

class HolidayCreate(CreateView):
    model = Holidays
    fields = ['date_f','national_holiday','cuti_bersama']
    success_url = reverse_lazy('holidays:holidays_list')


class HolidayUpdate(UpdateView):
    model = Holidays
    fields = ['date_f','national_holiday','cuti_bersama']
    success_url = reverse_lazy('holidays:holidays_list')

class HolidayDelete(DeleteView):
    model = Holidays
    success_url = reverse_lazy('holidays:holidays_list')

# class HolidayDay():
#     i = Holidays.objects.first()
#     if i.values('date_f_month') + '-' + i.values('date_f_date') in National_Holiday_List:
#         print(National_Holiday_List, "Hari Libur Nasional")

#     elif i.values('date_f_month') + '-' + i.values('date_f_date') in Mass_Leave_List:
#         print(Mass_Leave_List, "Hari Cuti Bersama")

holidays/templates/holidays/holidays_confirm_delete.html
{% extends "base.html" %}

{% block content %}

<h2><a href="{% url 'holidays:holidays_list' %}">Holidays</a>: Delete?</h2>

<form method="post">{% csrf_token %}
    Are you sure you want to delete "{{ object }}" ?<br>
    <input type="submit" value="Delete" />
</form>

{% endblock %}

holidays/templates/holidays/holidays_form.html
{% extends "base.html" %}

{% block content %}

<h2><a href="{% url 'holidays:holidays_list' %}">Holidays</a>: Edit</h2>

<form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit" />
</form>

{% endblock %}

holidays/templates/holidays/holidays_list.html
{% extends "base.html" %}

{% block content %}

<h2><a href="{% url 'holidays:holidays_list' %}">Holidays</a></h2>
 {% for holidays in object_list %}
 <fieldset>
<table border="1">
<thead>
    <th>Date                :</th>
    <th>National_Holidays   :</th>
    <th>Mass_Leave          :</th>>
</thead>
<tbody>
    <td><a>{{ holidays.date_f }}</a></td>
    <td><a>{{ holidays.national_holidays }}</a></td>
    <td><a>{{ holidays.cuti_bersama}}</a></td>
    <td><a href="{% url 'holidays:holidays_edit' holidays.id %}">edit</a></td>
    <td><a href="{% url 'holidays:holidays_delete' holidays.id %}">delete</a></td>
</tbody>
{% endfor %}
{% comment %} <ul><li></li></ul> {% endcomment %}

<a href="{% url 'holidays:holidays_new' %}">New</a>
</table>
</fieldset>
{% endblock %}

{% comment %} (No: {{ employee.no }})  {% endcomment %}
    {% comment %} (Name: {{ employee.name }})  {% endcomment %}
    {% comment %} (Position: {{ employee.position}})  {% endcomment %}
    {% comment %} (Address: {{ employee.address }})  {% endcomment %}
    {% comment %} (Phone: {{ employee.phone }})  {% endcomment %}
    {% comment %} (Email: {{ employee.email }}) {% endcomment %}
    {% comment %} <a href="{% url 'employee_cbv:employee_edit' employee.id %}">edit</a>
    <a href="{% url 'employee_cbv:employee_delete' employee.id %}">delete</a> {% endcomment %}