Apps/urls.py
from django.urls import include, path
from django.contrib import admin

from theme import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('employee_cbv/', include('employee_cbv.urls', namespace='employee_cbv')),
    #path('employee_attendance/', include('employee_attendance', namespace='employee_attendance')),
    #path('auth_ua/', include('auth_ua', namespace='auth_ua')),
    #path('holidays/', include('holidays', namespace='holidays')),
    #path('books_fbv_user/', include('books_fbv_user.urls', namespace='books_fbv_user')),
    path('', views.home),
]

employee_cbv/urls.py
from django.urls import path

from . import views

app_name = 'employee_cbv'

urlpatterns = [
  path('', views.EmployeeList.as_view(), name='employee_list'),
  path('new', views.EmployeeCreate.as_view(), name='employee_new'),
  path('edit/<int:pk>', views.EmployeeUpdate.as_view(), name='employee_edit'),
  path('delete/<int:pk>', views.EmployeeDelete.as_view(), name='employee_delete'),
]

employee_cbv/models.py
from django.db import models
from django.urls import reverse

# Create your models here.
#class Position(models.Model):

    #def __str__(self):
     #   return self.nameposition

    #nameposition = models.CharField(max_length=100,choices=POSITION_CHS)
   # keterangan = models.TextField(blank=True)

    

 #jenis_kelamin = models.CharField(max_length=10, choices=JENIS_KELAMIN_CHOICES, on_delete=models.CASCADE)

class Employee(models.Model):

    POSITION_CHS = (
        ('Manager', 'Manager'),
        ('Staff Admin', 'Staff Admin'),
        ('Staff Keuangan', 'Staff Keuangan'),
        ('Staff Marketing', 'Staff Marketing'),
    )

    no = models.CharField(max_length=30)
    name = models.CharField(max_length=90)
    position = models.CharField(max_length=30, choices=POSITION_CHS)
    address = models.TextField(max_length=100)
    phone = models.CharField(max_length=20)
    email = models.CharField(max_length=50)


    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('employee_cbv:employee_edit', kwargs={'pk': self.pk})

employee_cbv/views.py
from django.http import HttpResponse
from django.views.generic import TemplateView,ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy

from employee_cbv.models import Employee
# Create your views here.


class EmployeeList(ListView):
    model = Employee

class EmployeeCreate(CreateView):
    model = Employee
    fields = ['no','name', 'position','address','phone','email']
    success_url = reverse_lazy('employee_cbv:employee_list')


class EmployeeUpdate(UpdateView):
    model = Employee
    fields = ['no','name', 'position','address','phone','email']
    success_url = reverse_lazy('employee_cbv:employee_list')

class EmployeeDelete(DeleteView):
    model = Employee
    success_url = reverse_lazy('employee_cbv:employee_list')

employee_cbv/templates/employee_cbv/employee_confirm_delete.html
{% extends "base.html" %}

{% block content %}

<h2><a href="{% url 'employee_cbv:employee_list' %}">Employee CBV</a>: Delete?</h2>

<form method="post">{% csrf_token %}
    Are you sure you want to delete "{{ object }}" ?<br>
    <input type="submit" value="Delete" />
</form>

{% endblock %}

employee_cbv/templates/employee_cbv/employee_form.html
{% extends "base.html" %}

{% block content %}

<h2><a href="{% url 'employee_cbv:employee_list' %}">Employee CBV</a>: Edit</h2>

<form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit" />
</form>

{% endblock %}

employee_cbv/templates/employee_cbv/employee_list.html
{% extends "base.html" %}

{% block content %}

<h2><a href="{% url 'employee_cbv:employee_list' %}">Employee CBV</a></h2>
 {% for employee in object_list %}
 <fieldset>
<table border="1">
<thead>
    <th>No          :</th>
    <th>Name        :</th>
    <th>Position    :</th>
    <th>Address     :</th>
    <th>Phone       :</th>
    <th>Email       :</th>
    <th></th>
    <th></th>
</thead>
<tbody>
    <td><a>{{ employee.no }}</a></td>
    <td><a>{{ employee.name }}</a></td>
    <td><a>{{ employee.position}}</a></td>
    <td><a>{{ employee.address }}</a></td>
    <td><a>{{ employee.phone }}</a></td>
    <td><a>{{ employee.email }}</a></td>
    <td><a href="{% url 'employee_cbv:employee_edit' employee.id %}">edit</a></td>
    <td><a href="{% url 'employee_cbv:employee_delete' employee.id %}">delete</a></td>
</tbody>
{% endfor %}
{% comment %} <ul><li></li></ul> {% endcomment %}

<a href="{% url 'employee_cbv:employee_new' %}">New</a>
</table>
</fieldset>
{% endblock %}

{% comment %} (No: {{ employee.no }})  {% endcomment %}
    {% comment %} (Name: {{ employee.name }})  {% endcomment %}
    {% comment %} (Position: {{ employee.position}})  {% endcomment %}
    {% comment %} (Address: {{ employee.address }})  {% endcomment %}
    {% comment %} (Phone: {{ employee.phone }})  {% endcomment %}
    {% comment %} (Email: {{ employee.email }}) {% endcomment %}
    {% comment %} <a href="{% url 'employee_cbv:employee_edit' employee.id %}">edit</a>
    <a href="{% url 'employee_cbv:employee_delete' employee.id %}">delete</a> {% endcomment %}